### ISSUE TITLE
Can not find wigner.fmt file to run examples

### ISSUE THREAD

**Issue by mahelz** [janberges/elphmod#2]
Dear developers,

I'm trying to run the example: cdw_1d 

I can not run the python code cdw_1d .py because the wigner.fmt file is missing in my directory. Is that a file that epw is supposed to give after me a calculation or can I get it with a module of elphmod ?

Thank you for your help.

Best,
Mahé

**Comment by janberges** [comment]
Dear Mahé,

Thank you for reporting an issue!

The file `wigner.fmt` is created by EPW, but only when using a patched version of the code. After reinstalling QE following [these instructions](https://github.com/janberges/elphmod/tree/master/patches), the example should hopefully work.

`wigner.fmt` contains the lattice vectors corresponding to the electron-phonon matrix elements in the Wannier and displacement basis stored in `work/C.epmatwp`.

Let me know if the problem persists.

Best regards,

Jan

**Comment by mahelz** [comment]
Thank you very much for your quick answer. I'll try that, I'll let you know.

Best,
Mahé

**Comment by mahelz** [comment]
It works perfectly now!

Thanks again.

Best regards,
Mahé

**Comment by janberges** [comment]
Great! Note that this 1D example is still a bit experimental. If you are also interested in CDW relaxation in 2D systems, you could have a look at `examples/kekule.py`, `examples/md`, or [this repository](https://github.com/janberges/nbs2cdw).
