### ISSUE TITLE
Quadrupole fit

### ISSUE THREAD

**Issue by Vandemoo** [janberges/elphmod#3]
Hi, 

Can you please create an example script to generate a quadrupole.fmt file using the ph_vs_epw example in the newest version of elphmod.

Thanks in advance.

**Comment by janberges** [comment]
Hi @Vandemoo,

Thank you for the suggestion! I have added `examples/quadrupole`, which is nothing but the example `fitQ` from [here](https://doi.org/10.24435/materialscloud:he-pv), adapted to changes in elphmod and using the same routine as `examples/ph_vs_epw` to obtain the reference data. Is that what you mean?

Working on this issue made me notice two bugs I recently introduced. They are fixed in 0a7a06b and dd814d3. Thanks for that! I have not uploaded a new version of elphmod to PyPI yet, so the new example currently only works with the latest version of the code in the respository.

Best regards,

Jan

**Comment by Vandemoo** [comment]
Thank you, I ran the example and got this error

Traceback (most recent call last):
  File "/mnt/c/Users/ademo/Desktop/fitQ/fitQ/quadrupole/quadrupole.py", line 15, in <module>
    elph = elphmod.elph.Model('work/TaS2.epmatwp', 'wigner.fmt', el, ph)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ademo/Desktop/fitQ/fitQ/elphmod/lib/python3.11/site-packages/elphmod/elph.py", line 248, in __init__
    self.Rk, self.dk, self.Rg, self.dg = bravais.read_wigner_file(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/ademo/Desktop/fitQ/fitQ/elphmod/lib/python3.11/site-packages/elphmod/bravais.py", line 1213, in read_wigner_file
    ndegen_q[:, na, ir] = integers()
    ~~~~~~~~^^^^^^^^^^^
**IndexError: index 19 is out of bounds for axis 2 with size 19**

**Comment by janberges** [comment]
This is the error fixed in dd814d3. I have now also updated the package on PyPI. If you upgrade elphmod with pip, the example should work. The fix should also become available on conda-forge in a few hours.

**Comment by Vandemoo** [comment]
Thanks so much! I did not see your response earlier, it worked! I downloaded the github repo, created a new virtual environment and re-installed. Although I got the quadrupole.fmt file I wanted which is the most important for me, I could not view the plot, I got the error below:

Plot results
/mnt/c/Users/ademo/Desktop/elph/elphmod/examples/quadrupole/quadrupole.py:181: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Secondly, I want to use this example as a template to for my own system of 40 (Ti=16 atoms, N= 16 atoms, O=8 atoms), 39 (Ti=15 atoms, N= 12 atoms, O=12 atoms), and 38 (Ti=14 atoms, N= 8 atoms, O=12 atoms) atoms respectively.
I saw that in your def objective(Q) shown below, you chose some preferred directions. How do I use this for my system assuming the system has no symmetry. Any recommendation is welcome. Thanks once again!

def objective(Q):
    ph.Q = np.zeros((ph.nat, 3, 3, 3))

    ph.Q[1, 1, 1, 1] = Q[0] # Ta y y y
    ph.Q[2, 1, 1, 1] = Q[1] # S  y y y
    ph.Q[2, 2, 1, 1] = Q[2] # S  z y y

    ph.Q[:, 0, 0, 1] = ph.Q[:, 0, 1, 0] = ph.Q[:, 1, 0, 0] = -ph.Q[:, 1, 1, 1]
    ph.Q[:, 2, 0, 0] = ph.Q[:, 2, 1, 1]

    ph.Q[0, :2] = ph.Q[2, :2]
    ph.Q[0, 2] = -ph.Q[2, 2]

    ph.Q[Q == 0.0] = 0.0 # avoid negative zeros

**Comment by janberges** [comment]
Thanks for testing it! Regarding the plotting, it seems you do not have an interactive Matplotlib backend available in your virtual environment, see this [(outdated) documentation](https://matplotlib.org/3.1.3/faq/virtualenv_faq.html). On Debian/Ubuntu, I also get this warning when the package `python3-tk` is not installed. Installing PyQt5 in the virtual environment via `python3 -m pip install pyqt5` solves the problem for me.

And yes, we only optimize the independent elements of the quadrupole tensors. Optimization without any constraints would break the point symmetries of the atomic sites. ([This page](https://www.cryst.ehu.es/) helps find independent elements for given tensors and symmetries.) If you really have no symmetries, you only have to make sure that `ph.Q` is symmetric in the last two indices. Something like the following should work (not tested):

    def objective(Q):
        Q = np.reshape(Q, (ph.nat, 3, 6))

        ph.Q = np.empty((ph.nat, 3, 3, 3))

        for na in range(nat):
            for i in range(3):
                Qxx, Qyy, Qzz, Qyz, Qxz, Qxy = Q[na, i]

                ph.Q[na, i, 0, 0] = Qxx
                ph.Q[na, i, 1, 1] = Qyy
                ph.Q[na, i, 2, 2] = Qzz
                ph.Q[na, i, 1, 2] = Qyz
                ph.Q[na, i, 2, 1] = Qyz
                ph.Q[na, i, 0, 2] = Qxz
                ph.Q[na, i, 2, 0] = Qxz
                ph.Q[na, i, 0, 1] = Qxy
                ph.Q[na, i, 1, 0] = Qxy
                ...

Note that you will most likely obtain quadrupole tensors that yield a good interpolation but do not necessarily match the physical ones. You should also consider performing the fitting on a representative set of q points (the example uses points between Γ and M for simplicity). Alternatively, you could compute the quadrupole tensors with ABINIT.

**Comment by Vandemoo** [comment]
Okay, thanks for your help.

Best regards
